### ISSUE TITLE
能否添加OPENAI_proxy功能

### ISSUE THREAD

**Issue by Doutianbao** [yinan-c/RSS-GPT#26]
如题，使用第三方代理的API

**Comment by yinan-c** [comment]
没问题，我这周末加一下

**Comment by yinan-c** [comment]
@Doutianbao hi，我在 dev branch 加了 proxy，是根据 https://github.com/openai/openai-python/issues/825 依样画葫芦加了一段。由于我没有第三方代理 API，可以麻烦你帮忙 fork dev branch 然后测试一下吗？

**Comment by lmm214** [comment]
填写的格式是主域名还是需要加上 /v1
测试提示密钥错误，好像这个参数没生效

**Comment by yinan-c** [comment]
我明天研究一下

**Comment by lmm214** [comment]
> @lmm214 Hi，请问你是如何添加的 OPENAI_PROXY 参数，我的理解是直接填一个 url 字符串 即可，我在最新的 commit 了更新了代码，更新了 OpenAI library 版本，加了个 OPENAI_BASE_URL 参数，把这些填到 repo secrets 里面再试一下吧，看看能不能行。 另外，我是根据以下修改的 proxy 部分的代码。 https://www.python-httpx.org/api/#client https://github.com/openai/openai-python#configuring-the-http-client

https://github.com/lmm214/RSS-GPT/blob/main/docs/wechat.log

没通过，OPENAI_BASE_URL 加的是主域名，测试结果如上

**Comment by yinan-c** [comment]
@lmm214  那你在最后加一个 /v1 试试看，至少在官方 URL https://api.openai.com/ 之后加上 /v1 成功了
