### ISSUE TITLE
I have a free account. Will RSS-GPT work for me?

### ISSUE THREAD

**Issue by StepHaze** [yinan-c/RSS-GPT#27]
I have a free OpenAI account. Will RSS-GPT work for me?

**Comment by yinan-c** [comment]
RSS-GPT does not require a ChatGPT plus subscription, but it requires a valid openAI API to use its AI functionality for now. 

With a free openAI account, you can get $5 credit in API usage, after that's expired you will have to pay the API usage. I hope that make sense.
