### ISSUE TITLE
你好，请问生成的rss源是在哪里查看呢？

### ISSUE THREAD

**Issue by YAHKLI** [yinan-c/RSS-GPT#37]
你好，请问生成的rss源是在哪里查看呢？

**Comment by yinan-c** [comment]
进入 github pages. username.github.io/RSS-GPT/ 如果设置正确，项目 README 就有

**Comment by YAHKLI** [comment]
[yahkli.github.io/RSS_GPT/](https://yahkli.github.io/RSS_GPT/)

**Comment by yinan-c** [comment]
你的库里没有自动 commit 的更新信息，可能是没有设置 github personal token 在 repo secrets？ 手动跑一次 action 试试看？

**Comment by YAHKLI** [comment]
谢谢你的耐心，尽管我还是没能搞定。。没有coding能力，搞github有点费劲

**Comment by yinan-c** [comment]
没事，应该跟着我博客中的教程走应该没啥问题。
